---
apiVersion: v1
kind: Service
metadata:
  name: coruscanthealth
  labels:
    app.kubernetes.io/name: coruscanthealth
spec:
  type: ClusterIP
  ports:
  - port: 52773
  selector:
    org: empire
    class: coruscanthealth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coruscanthealth
  labels:
    app.kubernetes.io/name: coruscanthealth
spec:
  replicas: 1
  selector:
    matchLabels:
      org: empire
      class: coruscanthealth
  template:
    metadata:
      labels:
        org: empire
        class: coruscanthealth
        app.kubernetes.io/name: coruscanthealth
    spec:
      containers:
      - name: coruscanthealth
        image: docker.io/sween/ciliumfhir
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: fx-6
  labels:
    org: empire
    class: medicaldroid
    app.kubernetes.io/name: fx-6
spec:
  containers:
  - name: fx-6
    image: docker.io/curlimages/curl
---
apiVersion: v1
kind: Pod
metadata:
  name: dd-13
  labels:
    org: empire
    class: medicaldroid
    app.kubernetes.io/name: dd-13
spec:
  containers:
  - name: dd-13
    image: docker.io/curlimages/curl
---
apiVersion: v1
kind: Pod
metadata:
  name: 2-1b
  labels:
    org: empire
    class: medicaldroid
    app.kubernetes.io/name: 2-1b
spec:
  containers:
  - name: 2-1b
    image: docker.io/curlimages/curl
---
apiVersion: v1
kind: Pod
metadata:
  name: payer
  labels:
    app.kubernetes.io/name: payer
    org: republic
    class: payer
spec:
  containers:
  - name: payer
    image: docker.io/curlimages/curl